
flib_version=0.2.1
flib_file=8173392


mod_id=strippablemushroomblocks
curse_slug=strippable-mushroom-blocks
modrinth_id=strippable-mushroom-blocks
curse_id=1642402
mod_version=1.0.0
mod_name=strippablemushroomblocks
mod_group_id=com.lothrazar.strippablemushroomblocks
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=strippablemushroomblocks
