
flib_version=0.2.10
flib_file=8704177


mod_id=strippablemushroomblocks
curse_slug=strippablemushroomblocks
modrinth_id=
curse_id=0
mod_version=0.0.0-SNAPSHOT
mod_name=strippablemushroomblocks
mod_group_id=com.lothrazar.strippablemushroomblocks
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=strippablemushroomblocks
